# ==============================================================================
# ESP32-S3 INTERCOM MINI - New TCP-based API
# ==============================================================================
#
# Uses the new intercom_api component with TCP streaming on port 6054.
# Clean YAML syntax with native platform entities (no lambdas!)
#
# HARDWARE:
#   - Board: ESP32-S3 Mini (4MB Flash, Quad PSRAM)
#   - Microphone: SPH0645 I2S MEMS (I2S_NUM_0) - has DC offset
#   - Speaker: MAX98357A I2S amplifier (I2S_NUM_1)
#   - LED: WS2812 RGB (GPIO21)
#
# GPIO PINOUT:
#   Microphone (SPH0645):
#     - WS/LRCLK: GPIO3
#     - SCK/BCLK: GPIO2
#     - SD/DIN:   GPIO4
#
#   Speaker (MAX98357A):
#     - LRC/LRCLK: GPIO6
#     - BCLK:      GPIO7
#     - DIN:       GPIO8
#
#   LED (WS2812):
#     - DATA: GPIO21
#
# ==============================================================================

substitutions:
  name: intercom-mini
  friendly_name: Intercom Mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: quad
  speed: 80MHz

# ==============================================================================
# CONNECTIVITY
# ==============================================================================
api:
  on_client_connected:
    - lambda: 'id(intercom).publish_entity_states();'

ota:
  - platform: esphome

logger:
  hardware_uart: UART0
  level: INFO
  logs:
    intercom_api: INFO
    component: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.18
  ap:
    ssid: "${name} Fallback"

# ==============================================================================
# EXTERNAL COMPONENTS
# ==============================================================================
external_components:
  - source:
      type: local
      path: esphome_components
    components: [intercom_api, esp_aec]

# ==============================================================================
# I2S AUDIO BUSES
# ==============================================================================
i2s_audio:
  # I2S Bus 0: SPH0645 Microphone
  - id: i2s_mic_bus
    i2s_lrclk_pin: GPIO3
    i2s_bclk_pin: GPIO2

  # I2S Bus 1: MAX98357A Speaker
  - id: i2s_spk_bus
    i2s_lrclk_pin: GPIO6
    i2s_bclk_pin: GPIO7

# ==============================================================================
# MICROPHONE (SPH0645)
# ==============================================================================
microphone:
  - platform: i2s_audio
    id: mic_component
    i2s_audio_id: i2s_mic_bus
    i2s_din_pin: GPIO4
    adc_type: external
    pdm: false
    bits_per_sample: 32bit
    sample_rate: 16000
    channel: left

# ==============================================================================
# SPEAKER (MAX98357A)
# ==============================================================================
speaker:
  - platform: i2s_audio
    id: spk_component
    i2s_audio_id: i2s_spk_bus
    i2s_dout_pin: GPIO8
    dac_type: external
    i2s_mode: primary
    sample_rate: 16000
    bits_per_sample: 16bit
    timeout: never
    buffer_duration: 100ms

# ==============================================================================
# AEC (Acoustic Echo Cancellation)
# ==============================================================================
esp_aec:
  id: aec_processor
  sample_rate: 16000
  filter_length: 4
  mode: voip_low_cost

# ==============================================================================
# INTERCOM API (TCP-based, port 6054)
# ==============================================================================
# Auto-creates these sensors:
#   - text_sensor.intercom_mini_intercom_state (Idle/Ringing/Streaming)
#   - text_sensor.intercom_mini_destination (selected contact) [PTMP only]
#   - text_sensor.intercom_mini_caller (who is calling) [PTMP only]
#   - text_sensor.intercom_mini_contacts (count) [PTMP only]

intercom_api:
  id: intercom
  mode: ptmp                  # Multi-device mode with contacts
  microphone: mic_component
  speaker: spk_component
  mic_bits: 32                # SPH0645 is 32-bit I2S mic
  dc_offset_removal: true     # Required for SPH0645 (has DC bias)
  aec_id: aec_processor
  ringing_timeout: 30s        # Auto-decline if not answered

  # === New FSM triggers ===
  on_incoming_call:
    - logger.log: "Incoming call"

  on_outgoing_call:
    # ESP-to-ESP bridge is handled automatically by HA detecting state change to "Outgoing"
    - logger.log: "Outgoing call - HA will auto-start bridge"
    - light.turn_on:
        id: status_led
        effect: "Ringing"
        red: 100%
        green: 50%
        blue: 0%

  on_ringing:
    - light.turn_on:
        id: status_led
        effect: "Ringing"
        red: 100%
        green: 0%
        blue: 0%

  on_answered:
    - logger.log: "Call answered"

  on_streaming:
    - light.turn_on:
        id: status_led
        effect: "None"
        red: 0%
        green: 100%
        blue: 0%

  on_idle:
    - light.turn_off: status_led

  on_hangup:
    - logger.log:
        format: "Hangup: %s"
        args: ['reason.c_str()']

  on_call_failed:
    - logger.log:
        format: "Call failed: %s"
        args: ['reason.c_str()']

# ==============================================================================
# BUTTONS
# ==============================================================================
button:
  # Smart Call button: handles both HA doorbell and ESP-to-ESP calls
  - platform: template
    id: call_button
    name: "Call"
    icon: "mdi:phone"
    on_press:
      - if:
          condition:
            lambda: 'return strcmp(id(intercom).get_state_str(), "Ringing") == 0;'
          then:
            - intercom_api.answer_call:
                id: intercom
          else:
            - if:
                condition:
                  lambda: 'return strcmp(id(intercom).get_state_str(), "Streaming") == 0;'
                then:
                  - intercom_api.stop:
                      id: intercom
                else:
                  # Idle - check destination
                  - if:
                      condition:
                        lambda: 'return id(intercom).get_current_destination() == "Home Assistant";'
                      then:
                        - homeassistant.event:
                            event: esphome.doorbell_ring
                            data:
                              device: "${friendly_name}"
                      else:
                        - intercom_api.start:
                            id: intercom

  # Next contact (PTMP)
  - platform: template
    id: next_contact_button
    name: "Next Contact"
    icon: "mdi:arrow-right"
    on_press:
      - intercom_api.next_contact:
          id: intercom

  # Previous contact (PTMP)
  - platform: template
    id: prev_contact_button
    name: "Previous Contact"
    icon: "mdi:arrow-left"
    on_press:
      - intercom_api.prev_contact:
          id: intercom

  # Decline incoming call
  - platform: template
    id: decline_button
    name: "Decline"
    icon: "mdi:phone-hangup"
    on_press:
      - intercom_api.decline_call:
          id: intercom

  - platform: template
    id: refresh_contacts_button
    name: "Refresh Contacts"
    icon: "mdi:refresh"
    entity_category: config
    on_press:
      - intercom_api.set_contacts:
          id: intercom
          contacts_csv: !lambda 'return id(ha_active_devices).state;'

  - platform: restart
    name: "Restart"
    icon: "mdi:restart"

# ==============================================================================
# SWITCHES (native platform with restore_mode)
# ==============================================================================
switch:
  - platform: intercom_api
    intercom_api_id: intercom
    auto_answer:
      id: auto_answer_switch
      name: "Auto Answer"
      restore_mode: RESTORE_DEFAULT_ON
    aec:
      id: aec_switch
      name: "Echo Cancellation"
      restore_mode: RESTORE_DEFAULT_OFF

# ==============================================================================
# NUMBERS (native platform with restore_value)
# ==============================================================================
number:
  - platform: intercom_api
    intercom_api_id: intercom
    speaker_volume:
      id: speaker_volume
      name: "Speaker Volume"
    mic_gain:
      id: mic_gain
      name: "Mic Gain"

# ==============================================================================
# STATUS LED (WS2812 RGB on GPIO21)
# ==============================================================================
light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    icon: "mdi:led-on"
    pin: GPIO21
    chipset: WS2812
    num_leds: 1
    rgb_order: RGB
    effects:
      - pulse:
          name: "Streaming"
          min_brightness: 20%
          max_brightness: 100%
      - strobe:
          name: "Ringing"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 250ms
            - state: false
              duration: 250ms

# ==============================================================================
# TEXT SENSORS
# ==============================================================================
text_sensor:
  # Subscribe to HA's centralized contacts sensor
  - platform: homeassistant
    id: ha_active_devices
    entity_id: sensor.intercom_active_devices
    on_value:
      - intercom_api.set_contacts:
          id: intercom
          contacts_csv: !lambda 'return x;'

# ==============================================================================
# DIAGNOSTICS
# ==============================================================================
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 60s

  - platform: internal_temperature
    name: "CPU Temperature"
    update_interval: 60s
